otel_quarkus1.13Final
devonfw-forge/devonfw-microservices pull request #25
Opened 2021-05-10 09:26 UTC by SchneiderMalte

openTelemetry integration with Quarkus version 1.13.0Final. DISCLAIMER: Due to incompatibility with tkit-quarkus-jpa based on Quarkus version 1.12 currently not executable.

2021-05-10 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw-forge/devonfw-microservices?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw-forge/devonfw-microservices?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw-forge/devonfw-microservices?pullRequest=25) it.</sub>

2021-05-19 05:14 UTC, maybeec requested changes

2021-05-19 05:14 UTC, maybeec commented on reference-project/prometheus.yaml
> + # - url: http://victoriametrics:8428/api/v1/write
ifi not needed, please remove the comments

2021-05-19 05:14 UTC, maybeec commented on reference-project/src/main/java/com/devonfw/application/quarkus/sample/animalmanagement/logic/impl/AnimalDAO.java
> +//import org.eclipse.microprofile.opentracing.Traced;
same here.

2021-05-19 05:14 UTC, maybeec commented on reference-project/src/main/java/com/devonfw/application/quarkus/sample/animalmanagement/logic/impl/AnimalDAO.java
> +//@Traced
same

2021-05-19 05:14 UTC, maybeec commented on reference-project/src/main/java/com/devonfw/application/quarkus/sample/animalmanagement/logic/impl/AnimalDAO.java
> +    //this.tracer.activeSpan().setTag("predicates", predicates.size()).setTag("layer", "dao");
why is this uncommented?

2021-05-19 05:14 UTC, maybeec commented on reference-project/src/main/resources/application.properties
> +#quarkus.jaeger.endpoint=http://localhost:14268/api/traces
all not needed?

2021-06-10 16:43 UTC, hohwille reviewed
@SchneiderMalte thanks for this PR and your great work 👍 
This looks like a good improvement to me.
If only have the following questions:
* there seems to be no CI established for this repo, therefore I can only give a rought gut feeling about the quality of this change. Would it make sense that you give a demo in one of our standups so we ensure it is working (I believe you have tested this but working without CI gives me a bad feeling and we should also create another story to add github actions)
* You so far addressed REST. This is the most important aspect so far and great for the first PR so I am happy to merge this. However, to complete this story on the long run we should not forget about other aspects. What about opentelemtry for Kafka, JMS, JDBC, etc.? Please do not get me wrong: I do not want to have this all in this PR. We only need to add these aspects to our backlog before closing the opentelemetry story.

2021-06-18 16:23 UTC, hohwille commented
BTW: I changed the title to give a chance what this PR is about. You added the `[DRAFT]` prefix.
Can you follow github features for this next time?
https://github.blog/2019-02-14-introducing-draft-pull-requests/
Thanks

2021-06-23 11:16 UTC, merged